### ISSUE TITLE
 learn mathematical model

### ISSUE THREAD

**Issue by panchao12345** [online-ml/deep-river#96] opened 2024-11-14 04:00 UTC
The autonomous surface vehicles (ASVs) dynamic model is the mathematical model of its motion. Given the current state, velocity, and control inputs, the next state can be predicted based on the learned mathematical model. The model is as depicted in the figure. Can River learn?   
![1111](https://github.com/user-attachments/assets/bfabb393-4e67-4fc1-ac78-d321f6c7a742)

**Comment by kulbachcedric** [comment] 2024-11-14 17:03
Hi @panchao12345,
For me it seems to be a multi target regression problem to be solved, which generally can be solved with river. Could you provide an example?
Best
Cedric

**Comment by panchao12345** [comment] 2024-11-15 02:51
@kulbachcedric      I’m currently exploring the possibility of using River to solve this problem. I think it could be a good fit, but I’m still in the early stages of brainstorming and shaping the approach. At this point, I haven’t finalized the specific steps or methodology yet. I want to make sure I’ve fully thought through the process to ensure it’s the best solution. Once I have a more concrete plan in place, I’ll be able to share some examples and provide a clearer idea of how it could work.

**Comment by kulbachcedric** [comment] 2024-11-18 06:11
@panchao12345, sounds good to me. 
Whenever you know how your data looks like you can open a new issue.
For now, I think we can close it here. 

Best
Cedric

**Closed by kulbachcedric** 2024-11-18 06:11 UTC
